tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/core"
brew "awscli"
brew "bash-completion"
brew "bash-git-prompt"
brew "curl"
brew "htop"
brew "mas"
brew "wget"
cask "calibre"
cask "cyberduck"
cask "docker"
cask "firefox"
cask "github"
cask "google-chrome"
cask "handbrake"
cask "libreoffice"
cask "macs-fan-control"
cask "onyx"
cask "openemu"
cask "pacifist"
cask "phpstorm"
cask "postman"
cask "slack"
cask "sublime-text"
cask "suspicious-package"
cask "transmission"
cask "vlc"
mas "Affinity Photo", id: 824183456
mas "GrandPerspective", id: 1111570163
mas "MediaInfo", id: 510620098
mas "OmniFocus", id: 867299399
