tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/php"
brew "awscli"
brew "curl"
brew "git-lfs"
brew "htop"
brew "mas"
brew "percona-toolkit"
brew "wget"
brew "homebrew/php/composer"
brew "homebrew/php/php56"
brew "homebrew/php/php56-intl"
brew "homebrew/php/php56-mcrypt"
cask "calibre"
cask "cyberduck"
cask "docker"
cask "dropbox"
cask "firefox"
cask "github-desktop"
cask "google-chrome"
cask "lastpass"
cask "macupdate-desktop"
cask "onyx"
cask "phpstorm"
cask "postman"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "sublime-text"
cask "suspicious-package"
cask "tunnelblick"
cask "vlc"
cask "yujitach-menumeters"
mas "Affinity Photo", id: 824183456
mas "GarageBand", id: 682658836
mas "GrandPerspective", id: 1111570163
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "OmniFocus", id: 867299399
mas "Pages", id: 409201541
